baseURL = 'https://encrypted-file.zip/'
languageCode = 'en-us'
title = 'Welcome to Night City'
copyright = "Mike"


# Parameters
[params]
    subtitle = "Boom Whatup"
    dateFmt = "02.01.2006 15:04"
    custom_css = ["css/style.css"]




# Header
[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1 
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2

    [[menu.main]]
        identifier = "media"
        name = "Media"
        url = "/media/"
        weight = 3  

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/mbhuUM"
        weight = 1 


